### ISSUE TITLE
Basset from within a bundle

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#27]
I'm getting a lot of issues when trying to make Basset work from within a bundle.
One of the main problems I'm getting is this. From the **routes.php** of my bundle folder (so bundles/myBundle/routes.php) if I do the following (after the `Bundle::start('basset')` of course) :

``` php
<?php
Basset::styles('styles', function($basset)
{
  $basset->add('styles', 'bundles/myBundle/css/styles.css');
});
```

I can indeed access the `/public/bundles/myBundle/css/styles.css` file. Now if I do this :

``` php
<?php
Basset::styles('styles', function($basset)
{
  $basset->add('styles', 'myBundle::styles.css');
});
```

Althout still working I get errors thrown on my page :

```
Unhandled Exception

Message:

Undefined index: directory
Location:

/Applications/MAMP/htdocs/reservation/bundles/basset/classes/asset.php on line 175
Stack Trace:

#0 /Applications/MAMP/htdocs/reservation/laravel/laravel.php(40): Laravel\Error::native(8, 'Undefined index...', '/Applications/M...', 175)
#1 /Applications/MAMP/htdocs/reservation/bundles/basset/classes/asset.php(175): Laravel\{closure}(8, 'Undefined index...', '/Applications/M...', 175, Array)
#2 /Applications/MAMP/htdocs/reservation/bundles/basset/classes/asset.php(108): Basset\Asset->__get('directory')
#3 /Applications/MAMP/htdocs/reservation/bundles/basset/classes/container.php(305): Basset\Asset->get(Array, '')
#4 /Applications/MAMP/htdocs/reservation/bundles/basset/classes/basset.php(134): Basset\Container->compile()
#5 /Applications/MAMP/htdocs/reservation/bundles/basset/start.php(63): Basset::compile()
#6 [internal function]: {closure}(Object(Laravel\Response))
#7 /Applications/MAMP/htdocs/reservation/laravel/event.php(199): call_user_func_array(Object(Closure), Array)
#8 /Applications/MAMP/htdocs/reservation/laravel/laravel.php(219): Laravel\Event::fire('laravel.done', Array)
#9 /Applications/MAMP/htdocs/reservation/public/index.php(34): require('/Applications/M...')
#10 {main}
```

---

Most flags also seem to not work from a bundle, per example the following code style output only one link (even if I empty Basset and Laravel's cache) :

``` php
<?php
Basset::styles('styles', function($basset)
{
  $basset
    ->add('bootstrap', 'bundles/reservation/css/bootstrap.min.css')
    ->add('styles', 'bundles/reservation/css/styles.css')
    ->development()
  ;
});
```

While the compress() flag throws an error :

```
Unhandled Exception
Message:
Class 'Basset\Basset\Vendor\CSSCompress' not found
Location:
/Applications/MAMP/htdocs/reservation/bundles/basset/classes/container.php on line 327
```

It's so weird and crashing here and there that I'm truly wondering if there's not an extra step somewhere I'd have to take that would make it all work ?
Basset is correctly loaded in `bundles.php` asset described in the docs (`handles => 'basset', 'auto' => true`), I used `Bundle::start('basset')` at the beginning of my bundle's route.php, what is the next step ?

**Comment by jasonlewis** [comment]
Thanks for this, should be now fixed in the latest 2.0.1 release.
